### PR TITLE
Corrects examples

### LINKED ISSUE #22: Server example in README.md should make use of "variable"
To make clear what this actually means and what it is good for

### PR DESCRIPTION
**Pull request by s373r**
Now examples from README.md can be build

Also, closes #22

### CODE REVIEW

**Review by zeenix — CHANGES_REQUESTED** [review]
Thanks, the code looks good but the commit log could be improved.

* "Examples use 'variable'" makes me think that examples already use variable and that is a problem you're solving, which is the opposite of what you're doing.

* "It's about #22" -> "Resolves #22"?

It's always good to have some description in the log, esepcially if someone else is going to review. :) I follow these conventions and if you could update your commit logs to do that same, I'd be much obliged:

https://wiki.gnome.org/Git/CommitMessages/

**Comment by s373r** [comment]
Hello @zeenix !

Thank you for the quick reply and sorry for my late response.
Also, thanks for the link!

I've updated commit message - please check new changes.
I hope it's a clear text :)

**Review by zeenix — CHANGES_REQUESTED** [review]
Thanks so much. Looks good now. Two nits still:

* Corrects quick -> Update
* early -> previously.

**Comment by s373r** [comment]
@zeenix, thanks for correcting!

> Corrects quick -> Update
> early -> previously.

done

**Comment by zeenix** [comment]
Merged, thanks. :)

**Pull request merged**
